Upgraded from packages from Version 10.0.50 to 10.0.70 to resolve Exception Unhandled error.
Exception Unhandled

Java.Lang.IllegalArgumentException: 'No view found for id 0x7f0800f8 (com.missingchildrennm.kidsidkit:id/jumpToStart) for fragment NavigationRootManager_ElementBasedFragment{ab35c77} (b1f1a53f-d318-4688-8adc-c40aa81c7b87 id=0x7f0800f8)'